CREATE DATABASE IF NOT EXISTS kosmetikon;

\c kosmetikon;

CREATE TABLE IF NOT EXISTS raw_materials (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(80) NOT NULL,
    unit_of_measure VARCHAR(20) NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0.00 CHECK (quantity >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Note: In a production environment, PostgreSQL automatically manages `updated_at` via triggers if set up, 
-- but here we initialize it to current timestamp.

-- Optional Seed Data
INSERT INTO raw_materials (name, code, category, unit_of_measure, quantity, status, description)
VALUES 
    ('Water', 'RM-001', 'solvent', 'l', 500.00, 'active', 'Purified water for cosmetic formulations.'),
    ('Glycerin', 'RM-002', 'humectant', 'kg', 25.50, 'active', 'Vegetable glycerin.'),
    ('Sodium Laureth Sulfate', 'RM-003', 'surfactant', 'kg', 100.00, 'active', 'SLES, primary foaming agent.'),
    ('Phenoxyethanol', 'RM-004', 'preservative', 'kg', 5.00, 'active', 'Broad spectrum preservative.'),
    ('Discontinued Perfume', 'RM-005', 'fragrance', 'g', 0.00, 'inactive', 'Old fragrance formulation.'),
    ('Sample Material 1', 'RM-006', 'colorant', 'pcs', 463.76, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 2', 'RM-007', 'fragrance', 'pcs', 355.05, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 3', 'RM-008', 'colorant', 'pcs', 119.35, 'active', 'Autogenerated sample data.'),
    ('Sample Material 4', 'RM-009', 'rheology modifier', 'g', 282.35, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 5', 'RM-010', 'rheology modifier', 'ml', 383.44, 'active', 'Autogenerated sample data.'),
    ('Sample Material 6', 'RM-011', 'emulsifier', 'l', 120.56, 'active', 'Autogenerated sample data.'),
    ('Sample Material 7', 'RM-012', 'humectant', 'l', 191.68, 'active', 'Autogenerated sample data.'),
    ('Sample Material 8', 'RM-013', 'humectant', 'l', 381.52, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 9', 'RM-014', 'emulsifier', 'kg', 133.23, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 10', 'RM-015', 'preservative', 'pcs', 148.22, 'active', 'Autogenerated sample data.'),
    ('Sample Material 11', 'RM-016', 'preservative', 'pcs', 242.46, 'active', 'Autogenerated sample data.'),
    ('Sample Material 12', 'RM-017', 'preservative', 'g', 322.19, 'active', 'Autogenerated sample data.'),
    ('Sample Material 13', 'RM-018', 'humectant', 'l', 178.49, 'active', 'Autogenerated sample data.'),
    ('Sample Material 14', 'RM-019', 'rheology modifier', 'ml', 303.31, 'active', 'Autogenerated sample data.'),
    ('Sample Material 15', 'RM-020', 'active', 'g', 357.22, 'active', 'Autogenerated sample data.'),
    ('Sample Material 16', 'RM-021', 'emulsifier', 'kg', 260.59, 'active', 'Autogenerated sample data.'),
    ('Sample Material 17', 'RM-022', 'surfactant', 'ml', 212.82, 'active', 'Autogenerated sample data.'),
    ('Sample Material 18', 'RM-023', 'preservative', 'kg', 323.59, 'active', 'Autogenerated sample data.'),
    ('Sample Material 19', 'RM-024', 'fragrance', 'pcs', 282.95, 'active', 'Autogenerated sample data.'),
    ('Sample Material 20', 'RM-025', 'active', 'kg', 51.19, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 21', 'RM-026', 'preservative', 'ml', 489.49, 'active', 'Autogenerated sample data.'),
    ('Sample Material 22', 'RM-027', 'emulsifier', 'g', 328.24, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 23', 'RM-028', 'surfactant', 'ml', 310.67, 'active', 'Autogenerated sample data.'),
    ('Sample Material 24', 'RM-029', 'rheology modifier', 'kg', 4.52, 'active', 'Autogenerated sample data.'),
    ('Sample Material 25', 'RM-030', 'solvent', 'g', 159.12, 'active', 'Autogenerated sample data.'),
    ('Sample Material 26', 'RM-031', 'solvent', 'g', 372.52, 'active', 'Autogenerated sample data.'),
    ('Sample Material 27', 'RM-032', 'botanical extract', 'g', 403.69, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 28', 'RM-033', 'solvent', 'ml', 357.99, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 29', 'RM-034', 'preservative', 'ml', 51.94, 'active', 'Autogenerated sample data.'),
    ('Sample Material 30', 'RM-035', 'solvent', 'l', 193.38, 'active', 'Autogenerated sample data.'),
    ('Sample Material 31', 'RM-036', 'surfactant', 'g', 207.97, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 32', 'RM-037', 'fragrance', 'l', 468.32, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 33', 'RM-038', 'humectant', 'kg', 250.23, 'active', 'Autogenerated sample data.'),
    ('Sample Material 34', 'RM-039', 'fragrance', 'kg', 409.80, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 35', 'RM-040', 'surfactant', 'kg', 361.03, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 36', 'RM-041', 'surfactant', 'pcs', 45.25, 'active', 'Autogenerated sample data.'),
    ('Sample Material 37', 'RM-042', 'colorant', 'pcs', 196.96, 'active', 'Autogenerated sample data.'),
    ('Sample Material 38', 'RM-043', 'rheology modifier', 'pcs', 322.97, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 39', 'RM-044', 'botanical extract', 'pcs', 380.89, 'active', 'Autogenerated sample data.'),
    ('Sample Material 40', 'RM-045', 'solvent', 'g', 412.89, 'active', 'Autogenerated sample data.'),
    ('Sample Material 41', 'RM-046', 'surfactant', 'l', 213.78, 'active', 'Autogenerated sample data.'),
    ('Sample Material 42', 'RM-047', 'humectant', 'pcs', 444.63, 'active', 'Autogenerated sample data.'),
    ('Sample Material 43', 'RM-048', 'emulsifier', 'l', 249.74, 'active', 'Autogenerated sample data.'),
    ('Sample Material 44', 'RM-049', 'rheology modifier', 'pcs', 148.14, 'active', 'Autogenerated sample data.'),
    ('Sample Material 45', 'RM-050', 'solvent', 'l', 420.84, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 46', 'RM-051', 'preservative', 'kg', 207.69, 'inactive', 'Autogenerated sample data.'),
    ('Sample Material 47', 'RM-052', 'solvent', 'g', 149.05, 'active', 'Autogenerated sample data.'),
    ('Sample Material 48', 'RM-053', 'active', 'pcs', 437.31, 'active', 'Autogenerated sample data.'),
    ('Sample Material 49', 'RM-054', 'surfactant', 'g', 251.58, 'active', 'Autogenerated sample data.'),
    ('Sample Material 50', 'RM-055', 'colorant', 'l', 90.81, 'active', 'Autogenerated sample data.');
